function FindProxyForURL(url, host) {
    host = host.toLowerCase();

    var proxyServer = "PROXY 127.0.0.1:1080; DIRECT";

    // Список доменов из ru-blocked.list (пример)
    var proxy_hosts = [
        "chatgpt.com",
        "openai.com",
        "youtube.com",
        "youtu.be",
        "googlevideo.com",
        "ggpht.com",
        "ytimg.com",
        "facebook.com",
        "fbcdn.net",
        "instagram.com",
        "cdninstagram.com",
        "threads.net",
        "t.me",
        "telegram.org",
        "telegram.me",
        "telegram.dog",
        "twitter.com",
        "x.com",
        "linkedin.com",
        "discord.com",
        "discord.gg",
        "signal.org",
        "viber.com",
        "whatsapp.com",
        "web.whatsapp.com",
        "snapchat.com",
        "roblox.com",
        "cloudflare.com",
        "cloudflare.net",
        "patreon.com",
        "soundcloud.com",
        "spotify.com",
        "envato.com",
        "envatousercontent.com",
        "productboard.com",
        "whale.biz",
        "soundraw.io",
        "channel.io",
        "soundraw-storage.com",
        "makebestmusic.com",
        "gptunnel.ru",
        "mubert.com",
        "beatoven.ai",
        "musichero.ai",
        "soundful.com",
        "songgenerator.io",
        "toolful.ai",
        "erweima.ai",
        "aiquickdraw.com",
        "giphy.com",
        "slack.com",
        "medium.com",
        "tiktok.com",
        "grok.com",
        "x.ai",
        "openrouter.ai",
        "github.com",
        "githubusercontent.com",
        "gitlab.com",
        "stackoverflow.com",
        "imgur.com",
        "pixabay.com",
        "bbc.com",
        "bbc.co.uk",
        "dw.com",
        "moscowtimes.ru",
        "svoboda.org",
        "currenttime.tv",
        "torproject.org",
        "torproject.com",
        "windscribe.com",
        "apkmirror.com",
        "protonvpn.com",
        "expressvpn.com",
        "nordvpn.com",
        "surfshark.com",
        "bitcoin.org",
        "blockchain.com",
        "bitcointalk.org",
        "hashcat.net",
        "onlinehashcrack.com",
        "bitinfocharts.com",
        "zendesk.com",
        "clippie.ai",
        "vidiq.com",
        "trendshift.io",
        "wabbajack.org",
        "malavida.com",
        "doubleclick.net",
        "googletagmanager.com",
        "googleusercontent.com",
        "gds.google.com",
        "play.google.com",
        "auth.hentaicdn.org",
        "v3.animelib.org",
        "slashlib.me",
        "hentailib.me",
        "unrealsenseiacademy.com",
        "war.gov",
        "rockstargames.com",
        "metacritic.com",
        "soundcloud.com",
        "wix.com",
        "hubspot.com"
    ];

    if (isPlainHostName(host)) {
        return "DIRECT";
    }

    for (var i = 0; i < proxy_hosts.length; i++) {
        if (dnsDomainIs(host, proxy_hosts[i])) {
            return proxyServer;
        }
    }

    return "DIRECT";
}